const shoppingItems = [
  {
    id: 1,
    name: "Apple",
    category: "Fruits",
    price: 0.5,
    quantity: 10,
    description: "Fresh and juicy apples",
    imageUrl: "https://example.com/images/apple.jpg",
  },
  {
    id: 2,
    name: "Milk",
    category: "Dairy",
    price: 1.2,
    quantity: 2,
    description: "1 liter of whole milk",
    imageUrl: "https://example.com/images/milk.jpg",
  },
  {
    id: 3,
    name: "Bread",
    category: "Bakery",
    price: 2.5,
    quantity: 1,
    description: "Whole grain bread",
    imageUrl: "https://example.com/images/bread.jpg",
  },
  {
    id: 4,
    name: "Chicken Breast",
    category: "Meat",
    price: 5.0,
    quantity: 5,
    description: "Boneless and skinless chicken breast",
    imageUrl: "https://example.com/images/chicken_breast.jpg",
  },
  {
    id: 5,
    name: "Orange Juice",
    category: "Beverages",
    price: 3.0,
    quantity: 3,
    description: "Freshly squeezed orange juice",
    imageUrl: "https://example.com/images/orange_juice.jpg",
  },
  {
    id: 6,
    name: "Tomato",
    category: "Vegetables",
    price: 0.8,
    quantity: 8,
    description: "Fresh and ripe tomatoes",
    imageUrl: "https://example.com/images/tomato.jpg",
  },
  {
    id: 7,
    name: "Cheddar Cheese",
    category: "Dairy",
    price: 4.5,
    quantity: 1,
    description: "Aged cheddar cheese",
    imageUrl: "https://example.com/images/cheddar_cheese.jpg",
  },
  {
    id: 8,
    name: "Olive Oil",
    category: "Pantry",
    price: 6.0,
    quantity: 1,
    description: "Extra virgin olive oil",
    imageUrl: "https://example.com/images/olive_oil.jpg",
  },
  {
    id: 9,
    name: "Banana",
    category: "Fruits",
    price: 0.3,
    quantity: 12,
    description: "Ripe and sweet bananas",
    imageUrl: "https://example.com/images/banana.jpg",
  },
  {
    id: 10,
    name: "Yogurt",
    category: "Dairy",
    price: 0.9,
    quantity: 6,
    description: "Greek yogurt",
    imageUrl: "https://example.com/images/yogurt.jpg",
  },
];

export default shoppingItems;
